### ISSUE TITLE
Observed issues in Experiments feature

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#354]
**Frontend**

Bugs

* [ ] Edge case showing error "utils" is not defined for getExperiments when kernel crashed or sth bad happened (#381) .

* [x] How to handle Experiment with no parameters (no trials but one trial) in Launch Dialog? "All Trials" will trigger batch simulation but we don't have any exploration parameters. Should only allow to select "Base Model"?

* [x] Simulate button won't show LaunchDialog, only Model > Simulate

Improvements

* [x] JSONViewer performance issues with larger JSON files (#385)

* [x] Improve form validation - for existing params when editing an experiment, validation is not active because "field" wasn't fetched yet (#304)

* [ ] Available experiment parameters list should be updated when model changes (#386)

* [x] A user can create an arbitrary large number of trials with range type -> have to restrict that (#387)

**Backend**

Bugs

* [x] mpi - not enough slots available to statisfy 9 slots, although my machine has 16 cores (#372)

* [x] don't allow more than one experiment in design, have to delete existing experiment in design when we create a new one, currently just adding more experiments in design

* [x] Whitespaces in filenames cause issues for batch simulations (#384).

* [x] When we run a batch simulation and wait for the subprocess to complete, it never finishes. Some speciality with mpiexec? -> For now, all experiments will run non-blocking

Improvements

* [ ] EditExperiment is inefficient because it loads all trials, have to load trials only in view experiment (#388)
* [x] Successful simulation exists only when writing of data file is completed (or file exists) - Currently, using workaround to wait for data files since exit of a simulation doesn't mean that the file exists, write operation can be delayed (#383)

**Netpyne**

* [ ] `netpyne.metadata` is not up-to-date, type doesn't seem right in some cases (float vs list) and some fields are missing (#377)
